apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: chatbot
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'my-app'
      static_configs:
      - targets: ['10.96.162.128:7860']
