{
 "title": "MODEL FEEDBACK/RATING",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Feedback Count",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(feedback_stars_total{namespace=\"vectordb\"}) by (stars)\n"
    }
   ]
  },
  {
   "title": "AVERAGE RATING OF MODEL - GOOGLE/FLAN-T5-XL",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(feedback_stars_total{namespace=\"vectordb\"}))\n"
    }
   ]
  },
  {
   "title": "MODEL COUNT- GOOGLE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(model_usage_total{namespace=\"vectordb\", model_id=\"google/flan-t5-xl\"}) \n"
    }
   ]
  },
  {
   "title": "TGI Request Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tgi_request_count" }
   ]
  }
 ]
}