apiVersion: v1
kind: Pod
metadata:
  name: openshift-ai-pod
  labels:
    app: frontend
  namespace: prometheus 
spec:
  containers:
  - name: openshift-ai-container
    image: twinkllsisodia/ai-chatbot:latest
    env:
      - name: OPENAI_KEY
        valueFrom:
          secretKeyRef:
            name: openai-secret
            key: OPENAI_KEY
    ports:
    - containerPort: 7860 