apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sm
  namespace: chatbot
  labels:
    app: ai
spec:
  selector:
    matchLabels:
      app: ai
  namespaceSelector:
    matchNames:
    - chatbot    
  endpoints:
  - port: http