apiVersion: v1
kind: Service
metadata:
  name: openshift-ai-service
  namespace: ai-project
spec:
  selector:
    app: openshift-ai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7860
  type: ClusterIP
