{
 "title": "MODEL FEEDBACK/RATING",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "RATINGS - GOOGLE FLAN-T5",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(feedback_stars_total{namespace=\"vectordb\", model_id=\"google/flan-t5-xl\"}) by (stars)\n"
    }
   ]
  },
  {
   "title": "RATINGS - MISTRAL MODEL",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(feedback_stars_total{namespace=\"vectordb\", model_id=\"mistralai/Mistral-7B-Instruct-v0.1\"}) by (stars)\n"
    }
   ]
  },
  {
   "title": "AVERAGE RATING  - MISTRAL MODEL",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(feedback_stars_total{namespace=\"vectordb\", stars=\"1\", model_id=\"mistralai/Mistral-7B-Instruct-v0.1\"} * 1) + sum(feedback_stars_total{namespace=\"vectordb\", stars=\"2\", model_id=\"mistralai/Mistral-7B-Instruct-v0.1\"} * 2) +\nsum(feedback_stars_total{namespace=\"vectordb\", stars=\"3\", model_id=\"mistralai/Mistral-7B-Instruct-v0.1\"} * 3) + sum(feedback_stars_total{namespace=\"vectordb\", stars=\"4\", model_id=\"mistralai/Mistral-7B-Instruct-v0.1\"} * 4) +\nsum(feedback_stars_total{namespace=\"vectordb\", stars=\"5\", model_id=\"mistralai/Mistral-7B-Instruct-v0.1\"} * 5)) \n/\n(sum(feedback_stars_total{namespace=\"vectordb\", stars=\"1\", model_id=\"mistralai/Mistral-7B-Instruct-v0.1\"}) + sum(feedback_stars_total{namespace=\"vectordb\", stars=\"2\", model_id=\"mistralai/Mistral-7B-Instruct-v0.1\"}) + sum(feedback_stars_total{namespace=\"vectordb\", stars=\"3\", model_id=\"mistralai/Mistral-7B-Instruct-v0.1\"}) + sum(feedback_stars_total{namespace=\"vectordb\", stars=\"4\", model_id=\"mistralai/Mistral-7B-Instruct-v0.1\"}) + sum(feedback_stars_total{namespace=\"vectordb\", stars=\"5\", model_id=\"mistralai/Mistral-7B-Instruct-v0.1\"}))\n"
    }
   ]
  },
  {
   "title": "AVERAGE RATINGS - GOOGLE/FLAN-T5 MODEL",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(feedback_stars_total{namespace=\"vectordb\", stars=\"1\", model_id=\"google/flan-t5-xl\"} * 1) + sum(feedback_stars_total{namespace=\"vectordb\", stars=\"2\", model_id=\"google/flan-t5-xl\"} * 2) +\nsum(feedback_stars_total{namespace=\"vectordb\", stars=\"3\", model_id=\"google/flan-t5-xl\"} * 3) + sum(feedback_stars_total{namespace=\"vectordb\", stars=\"4\", model_id=\"google/flan-t5-xl\"} * 4) +\nsum(feedback_stars_total{namespace=\"vectordb\", stars=\"5\", model_id=\"google/flan-t5-xl\"} * 5)) \n/\n(sum(feedback_stars_total{namespace=\"vectordb\", stars=\"1\", model_id=\"google/flan-t5-xl\"}) + sum(feedback_stars_total{namespace=\"vectordb\", stars=\"2\", model_id=\"google/flan-t5-xl\"}) + sum(feedback_stars_total{namespace=\"vectordb\", stars=\"3\", model_id=\"google/flan-t5-xl\"}) + sum(feedback_stars_total{namespace=\"vectordb\", stars=\"4\", model_id=\"google/flan-t5-xl\"}) + sum(feedback_stars_total{namespace=\"vectordb\", stars=\"5\", model_id=\"google/flan-t5-xl\"}))\n"
    }
   ]
  },
  {
   "title": "MODEL USAGE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model_id) (model_usage_total{model_id=\"google/flan-t5-xl\"})",
     "legendFormat": "{{model_id}}"
    },
    {
     "expr": "sum by (model_id) (model_usage_total{model_id=\"mistralai/Mistral-7B-Instruct-v0.1\"})",
     "legendFormat": "{{model_id}}"
    }
   ]
  },
  {
   "title": "REQUEST TIME ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model_id) (request_duration_seconds{model_id=\"google/flan-t5-xl\"})",
     "legendFormat": "{{model_id}}"
    },
    {
     "expr": "sum by (model_id) (request_duration_seconds{model_id=\"mistralai/Mistral-7B-Instruct-v0.1\"})",
     "legendFormat": "{{model_id}}"
    }
   ]
  }
 ]
}